-- MySQL Script generated by MySQL Workbench
-- Thu Jun  6 23:05:51 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ConsejoDeFacultad
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ConsejoDeFacultad` ;

-- -----------------------------------------------------
-- Schema ConsejoDeFacultad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ConsejoDeFacultad` DEFAULT CHARACTER SET utf8 ;
USE `ConsejoDeFacultad` ;

-- -----------------------------------------------------
-- Table `ConsejoDeFacultad`.`MiembroConsejoFacultad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ConsejoDeFacultad`.`MiembroConsejoFacultad` (
  `idMiembroConsejoFacultad` NVARCHAR(30) NOT NULL,
  `NombreMiembro` VARCHAR(45) NOT NULL,
  `ApellidoPaternoMiembro` VARCHAR(45) NOT NULL,
  `ApellidoMaternoMiembro` VARCHAR(45) NOT NULL,
  `DNIMiembro` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`idMiembroConsejoFacultad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ConsejoDeFacultad`.`Decano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ConsejoDeFacultad`.`Decano` (
  `idDecano` NVARCHAR(30) NOT NULL,
  `MiembroConsejoFacultad_idMiembroConsejoFacultad` NVARCHAR(30) NOT NULL,
  PRIMARY KEY (`idDecano`),
  CONSTRAINT `fk_Decano_MiembroConsejoFacultad`
    FOREIGN KEY (`MiembroConsejoFacultad_idMiembroConsejoFacultad`)
    REFERENCES `ConsejoDeFacultad`.`MiembroConsejoFacultad` (`idMiembroConsejoFacultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Decano_MiembroConsejoFacultad_idx` ON `ConsejoDeFacultad`.`Decano` (`MiembroConsejoFacultad_idMiembroConsejoFacultad` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ConsejoDeFacultad`.`SecretarioDeActas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ConsejoDeFacultad`.`SecretarioDeActas` (
  `idSecretarioDeActas` NVARCHAR(30) NOT NULL,
  `NombreSecretario` VARCHAR(45) NOT NULL,
  `ApellidoPaternoSecretario` VARCHAR(45) NOT NULL,
  `ApellidoMaternoSecretario` VARCHAR(45) NOT NULL,
  `DNISecretario` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`idSecretarioDeActas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ConsejoDeFacultad`.`Sesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ConsejoDeFacultad`.`Sesion` (
  `idSesion` NVARCHAR(30) NOT NULL,
  `FechaSesion` DATE NOT NULL,
  `HoraInicio` VARCHAR(45) NOT NULL,
  `TipoSesion` VARCHAR(45) NOT NULL,
  `EstadoSesion` VARCHAR(15) NOT NULL,
  `Decano_idDecano` NVARCHAR(30) NOT NULL,
  `SecretarioDeActas_idSecretarioDeActas` NVARCHAR(30) NOT NULL,
  PRIMARY KEY (`idSesion`),
  CONSTRAINT `fk_Sesion_Decano1`
    FOREIGN KEY (`Decano_idDecano`)
    REFERENCES `ConsejoDeFacultad`.`Decano` (`idDecano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sesion_SecretarioDeActas1`
    FOREIGN KEY (`SecretarioDeActas_idSecretarioDeActas`)
    REFERENCES `ConsejoDeFacultad`.`SecretarioDeActas` (`idSecretarioDeActas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Sesion_Decano1_idx` ON `ConsejoDeFacultad`.`Sesion` (`Decano_idDecano` ASC) VISIBLE;

CREATE INDEX `fk_Sesion_SecretarioDeActas1_idx` ON `ConsejoDeFacultad`.`Sesion` (`SecretarioDeActas_idSecretarioDeActas` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ConsejoDeFacultad`.`Docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ConsejoDeFacultad`.`Docente` (
  `idDocente` NVARCHAR(30) NOT NULL,
  `TipoDocente` VARCHAR(45) NOT NULL,
  `GradoDocente` VARCHAR(45) NOT NULL,
  `MiembroConsejoFacultad_idMiembroConsejoFacultad` NVARCHAR(30) NOT NULL,
  PRIMARY KEY (`idDocente`),
  CONSTRAINT `fk_Docente_MiembroConsejoFacultad1`
    FOREIGN KEY (`MiembroConsejoFacultad_idMiembroConsejoFacultad`)
    REFERENCES `ConsejoDeFacultad`.`MiembroConsejoFacultad` (`idMiembroConsejoFacultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Docente_MiembroConsejoFacultad1_idx` ON `ConsejoDeFacultad`.`Docente` (`MiembroConsejoFacultad_idMiembroConsejoFacultad` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ConsejoDeFacultad`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ConsejoDeFacultad`.`Alumno` (
  `idAlumno` NVARCHAR(30) NOT NULL,
  `Escuela` VARCHAR(45) NOT NULL,
  `Serie` VARCHAR(45) NOT NULL,
  `MiembroConsejoFacultad_idMiembroConsejoFacultad` NVARCHAR(30) NOT NULL,
  PRIMARY KEY (`idAlumno`),
  CONSTRAINT `fk_Alumno_MiembroConsejoFacultad1`
    FOREIGN KEY (`MiembroConsejoFacultad_idMiembroConsejoFacultad`)
    REFERENCES `ConsejoDeFacultad`.`MiembroConsejoFacultad` (`idMiembroConsejoFacultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Alumno_MiembroConsejoFacultad1_idx` ON `ConsejoDeFacultad`.`Alumno` (`MiembroConsejoFacultad_idMiembroConsejoFacultad` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ConsejoDeFacultad`.`Acta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ConsejoDeFacultad`.`Acta` (
  `idActa` NVARCHAR(15) NOT NULL,
  `Nombre` NVARCHAR(50) NOT NULL,
  `HoraInicio` TIME NOT NULL,
  `HoraFin` TIME NOT NULL,
  `MiembroConsejoFacultad_idMiembroConsejoFacultad` NVARCHAR(30) NOT NULL,
  `SecretarioDeActas_idSecretarioDeActas` NVARCHAR(30) NOT NULL,
  PRIMARY KEY (`idActa`),
  CONSTRAINT `fk_Acta_MiembroConsejoFacultad1`
    FOREIGN KEY (`MiembroConsejoFacultad_idMiembroConsejoFacultad`)
    REFERENCES `ConsejoDeFacultad`.`MiembroConsejoFacultad` (`idMiembroConsejoFacultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Acta_SecretarioDeActas1`
    FOREIGN KEY (`SecretarioDeActas_idSecretarioDeActas`)
    REFERENCES `ConsejoDeFacultad`.`SecretarioDeActas` (`idSecretarioDeActas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Acta_MiembroConsejoFacultad1_idx` ON `ConsejoDeFacultad`.`Acta` (`MiembroConsejoFacultad_idMiembroConsejoFacultad` ASC) VISIBLE;

CREATE INDEX `fk_Acta_SecretarioDeActas1_idx` ON `ConsejoDeFacultad`.`Acta` (`SecretarioDeActas_idSecretarioDeActas` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ConsejoDeFacultad`.`Citacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ConsejoDeFacultad`.`Citacion` (
  `idCitacion` NCHAR(30) NOT NULL,
  `SecretarioDeActas_idSecretarioDeActas` NVARCHAR(30) NOT NULL,
  `Destinatario` NVARCHAR(50) NOT NULL,
  `FechaCitacion` NVARCHAR(50) NOT NULL,
  PRIMARY KEY (`idCitacion`),
  CONSTRAINT `fk_Citacion_SecretarioDeActas1`
    FOREIGN KEY (`SecretarioDeActas_idSecretarioDeActas`)
    REFERENCES `ConsejoDeFacultad`.`SecretarioDeActas` (`idSecretarioDeActas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Citacion_SecretarioDeActas1_idx` ON `ConsejoDeFacultad`.`Citacion` (`SecretarioDeActas_idSecretarioDeActas` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ConsejoDeFacultad`.`Proveido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ConsejoDeFacultad`.`Proveido` (
  `idProveido` NVARCHAR(30) NOT NULL,
  `SecretarioDeActas_idSecretarioDeActas` NVARCHAR(30) NOT NULL,
  `Nombre` NVARCHAR(50) NOT NULL,
  `FechaProveido` DATE NOT NULL,
  `Asunto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProveido`),
  CONSTRAINT `fk_Proveido_SecretarioDeActas1`
    FOREIGN KEY (`SecretarioDeActas_idSecretarioDeActas`)
    REFERENCES `ConsejoDeFacultad`.`SecretarioDeActas` (`idSecretarioDeActas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Proveido_SecretarioDeActas1_idx` ON `ConsejoDeFacultad`.`Proveido` (`SecretarioDeActas_idSecretarioDeActas` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ConsejoDeFacultad`.`Dictamen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ConsejoDeFacultad`.`Dictamen` (
  `idDictamen` INT NOT NULL,
  `NombreDocumento` NVARCHAR(50) NOT NULL,
  `EstadoDictamen` NVARCHAR(30) NOT NULL,
  PRIMARY KEY (`idDictamen`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ConsejoDeFacultad`.`GestionDictamen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ConsejoDeFacultad`.`GestionDictamen` (
  `MiembroConsejoFacultad_idMiembroConsejoFacultad` NVARCHAR(30) NOT NULL,
  `Dictamen_idDictamen` INT NOT NULL,
  `EstadoGestionDictamen` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`MiembroConsejoFacultad_idMiembroConsejoFacultad`, `Dictamen_idDictamen`),
  CONSTRAINT `fk_MiembroConsejoFacultad_has_Dictamen_MiembroConsejoFacultad1`
    FOREIGN KEY (`MiembroConsejoFacultad_idMiembroConsejoFacultad`)
    REFERENCES `ConsejoDeFacultad`.`MiembroConsejoFacultad` (`idMiembroConsejoFacultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MiembroConsejoFacultad_has_Dictamen_Dictamen1`
    FOREIGN KEY (`Dictamen_idDictamen`)
    REFERENCES `ConsejoDeFacultad`.`Dictamen` (`idDictamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_MiembroConsejoFacultad_has_Dictamen_Dictamen1_idx` ON `ConsejoDeFacultad`.`GestionDictamen` (`Dictamen_idDictamen` ASC) VISIBLE;

CREATE INDEX `fk_MiembroConsejoFacultad_has_Dictamen_MiembroConsejoFacult_idx` ON `ConsejoDeFacultad`.`GestionDictamen` (`MiembroConsejoFacultad_idMiembroConsejoFacultad` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
