package pe.edu.consejo.facultad.unsch.entities;
// Generated 07-jun-2019 8:17:32 by Hibernate Tools 5.4.2.Final

import java.util.Date;

/**
 * Acta generated by hbm2java
 */
public class Acta implements java.io.Serializable {

	private String idActa;
	private String nombre;
	private Date horaInicio;
	private Date horaFin;
	private String miembroConsejoFacultadIdMiembroConsejoFacultad;
	private String secretarioDeActasIdSecretarioDeActas;

	public Acta() {
	}

	public Acta(String idActa, String nombre, Date horaInicio, Date horaFin,
			String miembroConsejoFacultadIdMiembroConsejoFacultad, String secretarioDeActasIdSecretarioDeActas) {
		this.idActa = idActa;
		this.nombre = nombre;
		this.horaInicio = horaInicio;
		this.horaFin = horaFin;
		this.miembroConsejoFacultadIdMiembroConsejoFacultad = miembroConsejoFacultadIdMiembroConsejoFacultad;
		this.secretarioDeActasIdSecretarioDeActas = secretarioDeActasIdSecretarioDeActas;
	}

	public String getIdActa() {
		return this.idActa;
	}

	public void setIdActa(String idActa) {
		this.idActa = idActa;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(Date horaInicio) {
		this.horaInicio = horaInicio;
	}

	public Date getHoraFin() {
		return this.horaFin;
	}

	public void setHoraFin(Date horaFin) {
		this.horaFin = horaFin;
	}

	public String getMiembroConsejoFacultadIdMiembroConsejoFacultad() {
		return this.miembroConsejoFacultadIdMiembroConsejoFacultad;
	}

	public void setMiembroConsejoFacultadIdMiembroConsejoFacultad(
			String miembroConsejoFacultadIdMiembroConsejoFacultad) {
		this.miembroConsejoFacultadIdMiembroConsejoFacultad = miembroConsejoFacultadIdMiembroConsejoFacultad;
	}

	public String getSecretarioDeActasIdSecretarioDeActas() {
		return this.secretarioDeActasIdSecretarioDeActas;
	}

	public void setSecretarioDeActasIdSecretarioDeActas(String secretarioDeActasIdSecretarioDeActas) {
		this.secretarioDeActasIdSecretarioDeActas = secretarioDeActasIdSecretarioDeActas;
	}

}
