package pe.edu.consejo.facultad.unsch.entities;
// Generated 28-jun-2019 1:16:48 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Alumno generated by hbm2java
 */
@Entity
@Table(name = "alumno", catalog = "consejodefacultad")
public class Alumno implements java.io.Serializable {

	private String idAlumno;
	private Miembroconsejofacultad miembroconsejofacultad;
	private String escuela;
	private String serie;

	public Alumno() {
	}

	public Alumno(String idAlumno, Miembroconsejofacultad miembroconsejofacultad, String escuela, String serie) {
		this.idAlumno = idAlumno;
		this.miembroconsejofacultad = miembroconsejofacultad;
		this.escuela = escuela;
		this.serie = serie;
	}

	@Id

	@Column(name = "idAlumno", unique = true, nullable = false, length = 30)
	public String getIdAlumno() {
		return this.idAlumno;
	}

	public void setIdAlumno(String idAlumno) {
		this.idAlumno = idAlumno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MiembroConsejoFacultad_idMiembroConsejoFacultad", nullable = false)
	public Miembroconsejofacultad getMiembroconsejofacultad() {
		return this.miembroconsejofacultad;
	}

	public void setMiembroconsejofacultad(Miembroconsejofacultad miembroconsejofacultad) {
		this.miembroconsejofacultad = miembroconsejofacultad;
	}

	@Column(name = "Escuela", nullable = false, length = 45)
	public String getEscuela() {
		return this.escuela;
	}

	public void setEscuela(String escuela) {
		this.escuela = escuela;
	}

	@Column(name = "Serie", nullable = false, length = 45)
	public String getSerie() {
		return this.serie;
	}

	public void setSerie(String serie) {
		this.serie = serie;
	}

}
