package pe.edu.consejo.facultad.unsch.entities;
// Generated 07-jun-2019 8:17:32 by Hibernate Tools 5.4.2.Final

/**
 * Citacion generated by hbm2java
 */
public class Citacion implements java.io.Serializable {

	private String idCitacion;
	private String secretarioDeActasIdSecretarioDeActas;
	private String destinatario;
	private String fechaCitacion;

	public Citacion() {
	}

	public Citacion(String idCitacion, String secretarioDeActasIdSecretarioDeActas, String destinatario,
			String fechaCitacion) {
		this.idCitacion = idCitacion;
		this.secretarioDeActasIdSecretarioDeActas = secretarioDeActasIdSecretarioDeActas;
		this.destinatario = destinatario;
		this.fechaCitacion = fechaCitacion;
	}

	public String getIdCitacion() {
		return this.idCitacion;
	}

	public void setIdCitacion(String idCitacion) {
		this.idCitacion = idCitacion;
	}

	public String getSecretarioDeActasIdSecretarioDeActas() {
		return this.secretarioDeActasIdSecretarioDeActas;
	}

	public void setSecretarioDeActasIdSecretarioDeActas(String secretarioDeActasIdSecretarioDeActas) {
		this.secretarioDeActasIdSecretarioDeActas = secretarioDeActasIdSecretarioDeActas;
	}

	public String getDestinatario() {
		return this.destinatario;
	}

	public void setDestinatario(String destinatario) {
		this.destinatario = destinatario;
	}

	public String getFechaCitacion() {
		return this.fechaCitacion;
	}

	public void setFechaCitacion(String fechaCitacion) {
		this.fechaCitacion = fechaCitacion;
	}

}
