package pe.edu.consejo.facultad.unsch.entities;
// Generated 07-jun-2019 8:17:32 by Hibernate Tools 5.4.2.Final

/**
 * Decano generated by hbm2java
 */
public class Decano implements java.io.Serializable {

	private String idDecano;
	private String miembroConsejoFacultadIdMiembroConsejoFacultad;

	public Decano() {
	}

	public Decano(String idDecano, String miembroConsejoFacultadIdMiembroConsejoFacultad) {
		this.idDecano = idDecano;
		this.miembroConsejoFacultadIdMiembroConsejoFacultad = miembroConsejoFacultadIdMiembroConsejoFacultad;
	}

	public String getIdDecano() {
		return this.idDecano;
	}

	public void setIdDecano(String idDecano) {
		this.idDecano = idDecano;
	}

	public String getMiembroConsejoFacultadIdMiembroConsejoFacultad() {
		return this.miembroConsejoFacultadIdMiembroConsejoFacultad;
	}

	public void setMiembroConsejoFacultadIdMiembroConsejoFacultad(
			String miembroConsejoFacultadIdMiembroConsejoFacultad) {
		this.miembroConsejoFacultadIdMiembroConsejoFacultad = miembroConsejoFacultadIdMiembroConsejoFacultad;
	}

}
