package pe.edu.consejo.facultad.unsch.entities;
// Generated 28-jun-2019 1:16:48 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Decano generated by hbm2java
 */
@Entity
@Table(name = "decano", catalog = "consejodefacultad")
public class Decano implements java.io.Serializable {

	private String idDecano;
	private Miembroconsejofacultad miembroconsejofacultad;
	private Set<Sesion> sesions = new HashSet<Sesion>(0);

	public Decano() {
	}

	public Decano(String idDecano, Miembroconsejofacultad miembroconsejofacultad) {
		this.idDecano = idDecano;
		this.miembroconsejofacultad = miembroconsejofacultad;
	}

	public Decano(String idDecano, Miembroconsejofacultad miembroconsejofacultad, Set<Sesion> sesions) {
		this.idDecano = idDecano;
		this.miembroconsejofacultad = miembroconsejofacultad;
		this.sesions = sesions;
	}

	@Id

	@Column(name = "idDecano", unique = true, nullable = false, length = 30)
	public String getIdDecano() {
		return this.idDecano;
	}

	public void setIdDecano(String idDecano) {
		this.idDecano = idDecano;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MiembroConsejoFacultad_idMiembroConsejoFacultad", nullable = false)
	public Miembroconsejofacultad getMiembroconsejofacultad() {
		return this.miembroconsejofacultad;
	}

	public void setMiembroconsejofacultad(Miembroconsejofacultad miembroconsejofacultad) {
		this.miembroconsejofacultad = miembroconsejofacultad;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "decano")
	public Set<Sesion> getSesions() {
		return this.sesions;
	}

	public void setSesions(Set<Sesion> sesions) {
		this.sesions = sesions;
	}

}
