package pe.edu.consejo.facultad.unsch.entities;
// Generated 28-jun-2019 1:16:48 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Dictamen generated by hbm2java
 */
@Entity
@Table(name = "dictamen", catalog = "consejodefacultad")
public class Dictamen implements java.io.Serializable {

	private int idDictamen;
	private Miembroconsejofacultad miembroconsejofacultad;
	private String nombreDocumento;
	private String estadoDictamen;

	public Dictamen() {
	}

	public Dictamen(int idDictamen, Miembroconsejofacultad miembroconsejofacultad, String nombreDocumento,
			String estadoDictamen) {
		this.idDictamen = idDictamen;
		this.miembroconsejofacultad = miembroconsejofacultad;
		this.nombreDocumento = nombreDocumento;
		this.estadoDictamen = estadoDictamen;
	}

	@Id

	@Column(name = "idDictamen", unique = true, nullable = false)
	public int getIdDictamen() {
		return this.idDictamen;
	}

	public void setIdDictamen(int idDictamen) {
		this.idDictamen = idDictamen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MiembroConsejoFacultad_idMiembroConsejoFacultad", nullable = false)
	public Miembroconsejofacultad getMiembroconsejofacultad() {
		return this.miembroconsejofacultad;
	}

	public void setMiembroconsejofacultad(Miembroconsejofacultad miembroconsejofacultad) {
		this.miembroconsejofacultad = miembroconsejofacultad;
	}

	@Column(name = "NombreDocumento", nullable = false, length = 50)
	public String getNombreDocumento() {
		return this.nombreDocumento;
	}

	public void setNombreDocumento(String nombreDocumento) {
		this.nombreDocumento = nombreDocumento;
	}

	@Column(name = "EstadoDictamen", nullable = false, length = 30)
	public String getEstadoDictamen() {
		return this.estadoDictamen;
	}

	public void setEstadoDictamen(String estadoDictamen) {
		this.estadoDictamen = estadoDictamen;
	}

}
