package pe.edu.consejo.facultad.unsch.entities;
// Generated 07-jun-2019 8:17:32 by Hibernate Tools 5.4.2.Final

/**
 * Docente generated by hbm2java
 */
public class Docente implements java.io.Serializable {

	private String idDocente;
	private String tipoDocente;
	private String gradoDocente;
	private String miembroConsejoFacultadIdMiembroConsejoFacultad;

	public Docente() {
	}

	public Docente(String idDocente, String tipoDocente, String gradoDocente,
			String miembroConsejoFacultadIdMiembroConsejoFacultad) {
		this.idDocente = idDocente;
		this.tipoDocente = tipoDocente;
		this.gradoDocente = gradoDocente;
		this.miembroConsejoFacultadIdMiembroConsejoFacultad = miembroConsejoFacultadIdMiembroConsejoFacultad;
	}

	public String getIdDocente() {
		return this.idDocente;
	}

	public void setIdDocente(String idDocente) {
		this.idDocente = idDocente;
	}

	public String getTipoDocente() {
		return this.tipoDocente;
	}

	public void setTipoDocente(String tipoDocente) {
		this.tipoDocente = tipoDocente;
	}

	public String getGradoDocente() {
		return this.gradoDocente;
	}

	public void setGradoDocente(String gradoDocente) {
		this.gradoDocente = gradoDocente;
	}

	public String getMiembroConsejoFacultadIdMiembroConsejoFacultad() {
		return this.miembroConsejoFacultadIdMiembroConsejoFacultad;
	}

	public void setMiembroConsejoFacultadIdMiembroConsejoFacultad(
			String miembroConsejoFacultadIdMiembroConsejoFacultad) {
		this.miembroConsejoFacultadIdMiembroConsejoFacultad = miembroConsejoFacultadIdMiembroConsejoFacultad;
	}

}
