package pe.edu.consejo.facultad.unsch.entities;
// Generated 28-jun-2019 1:16:48 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Docente generated by hbm2java
 */
@Entity
@Table(name = "docente", catalog = "consejodefacultad")
public class Docente implements java.io.Serializable {

	private String idDocente;
	private Miembroconsejofacultad miembroconsejofacultad;
	private String tipoDocente;
	private String gradoDocente;

	public Docente() {
	}

	public Docente(String idDocente, Miembroconsejofacultad miembroconsejofacultad, String tipoDocente,
			String gradoDocente) {
		this.idDocente = idDocente;
		this.miembroconsejofacultad = miembroconsejofacultad;
		this.tipoDocente = tipoDocente;
		this.gradoDocente = gradoDocente;
	}

	@Id

	@Column(name = "idDocente", unique = true, nullable = false, length = 30)
	public String getIdDocente() {
		return this.idDocente;
	}

	public void setIdDocente(String idDocente) {
		this.idDocente = idDocente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MiembroConsejoFacultad_idMiembroConsejoFacultad", nullable = false)
	public Miembroconsejofacultad getMiembroconsejofacultad() {
		return this.miembroconsejofacultad;
	}

	public void setMiembroconsejofacultad(Miembroconsejofacultad miembroconsejofacultad) {
		this.miembroconsejofacultad = miembroconsejofacultad;
	}

	@Column(name = "TipoDocente", nullable = false, length = 45)
	public String getTipoDocente() {
		return this.tipoDocente;
	}

	public void setTipoDocente(String tipoDocente) {
		this.tipoDocente = tipoDocente;
	}

	@Column(name = "GradoDocente", nullable = false, length = 45)
	public String getGradoDocente() {
		return this.gradoDocente;
	}

	public void setGradoDocente(String gradoDocente) {
		this.gradoDocente = gradoDocente;
	}

}
