package pe.edu.consejo.facultad.unsch.entities;
// Generated 07-jun-2019 8:17:32 by Hibernate Tools 5.4.2.Final

/**
 * GestiondictamenId generated by hbm2java
 */
public class GestiondictamenId implements java.io.Serializable {

	private String miembroConsejoFacultadIdMiembroConsejoFacultad;
	private int dictamenIdDictamen;

	public GestiondictamenId() {
	}

	public GestiondictamenId(String miembroConsejoFacultadIdMiembroConsejoFacultad, int dictamenIdDictamen) {
		this.miembroConsejoFacultadIdMiembroConsejoFacultad = miembroConsejoFacultadIdMiembroConsejoFacultad;
		this.dictamenIdDictamen = dictamenIdDictamen;
	}

	public String getMiembroConsejoFacultadIdMiembroConsejoFacultad() {
		return this.miembroConsejoFacultadIdMiembroConsejoFacultad;
	}

	public void setMiembroConsejoFacultadIdMiembroConsejoFacultad(
			String miembroConsejoFacultadIdMiembroConsejoFacultad) {
		this.miembroConsejoFacultadIdMiembroConsejoFacultad = miembroConsejoFacultadIdMiembroConsejoFacultad;
	}

	public int getDictamenIdDictamen() {
		return this.dictamenIdDictamen;
	}

	public void setDictamenIdDictamen(int dictamenIdDictamen) {
		this.dictamenIdDictamen = dictamenIdDictamen;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GestiondictamenId))
			return false;
		GestiondictamenId castOther = (GestiondictamenId) other;

		return ((this.getMiembroConsejoFacultadIdMiembroConsejoFacultad() == castOther
				.getMiembroConsejoFacultadIdMiembroConsejoFacultad())
				|| (this.getMiembroConsejoFacultadIdMiembroConsejoFacultad() != null
						&& castOther.getMiembroConsejoFacultadIdMiembroConsejoFacultad() != null
						&& this.getMiembroConsejoFacultadIdMiembroConsejoFacultad()
								.equals(castOther.getMiembroConsejoFacultadIdMiembroConsejoFacultad())))
				&& (this.getDictamenIdDictamen() == castOther.getDictamenIdDictamen());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMiembroConsejoFacultadIdMiembroConsejoFacultad() == null ? 0
				: this.getMiembroConsejoFacultadIdMiembroConsejoFacultad().hashCode());
		result = 37 * result + this.getDictamenIdDictamen();
		return result;
	}

}
