package pe.edu.consejo.facultad.unsch.entities;
// Generated 07-jun-2019 8:17:32 by Hibernate Tools 5.4.2.Final

/**
 * Gestiondictamen generated by hbm2java
 */
public class Gestiondictamen implements java.io.Serializable {

	private GestiondictamenId id;
	private String estadoGestionDictamen;

	public Gestiondictamen() {
	}

	public Gestiondictamen(GestiondictamenId id, String estadoGestionDictamen) {
		this.id = id;
		this.estadoGestionDictamen = estadoGestionDictamen;
	}

	public GestiondictamenId getId() {
		return this.id;
	}

	public void setId(GestiondictamenId id) {
		this.id = id;
	}

	public String getEstadoGestionDictamen() {
		return this.estadoGestionDictamen;
	}

	public void setEstadoGestionDictamen(String estadoGestionDictamen) {
		this.estadoGestionDictamen = estadoGestionDictamen;
	}

}
