package pe.edu.consejo.facultad.unsch.entities;
// Generated 07-jun-2019 8:17:32 by Hibernate Tools 5.4.2.Final

/**
 * Miembroconsejofacultad generated by hbm2java
 */
public class Miembroconsejofacultad implements java.io.Serializable {

	private String idMiembroConsejoFacultad;
	private String nombreMiembro;
	private String apellidoPaternoMiembro;
	private String apellidoMaternoMiembro;
	private String dnimiembro;

	public Miembroconsejofacultad() {
	}

	public Miembroconsejofacultad(String idMiembroConsejoFacultad, String nombreMiembro, String apellidoPaternoMiembro,
			String apellidoMaternoMiembro, String dnimiembro) {
		this.idMiembroConsejoFacultad = idMiembroConsejoFacultad;
		this.nombreMiembro = nombreMiembro;
		this.apellidoPaternoMiembro = apellidoPaternoMiembro;
		this.apellidoMaternoMiembro = apellidoMaternoMiembro;
		this.dnimiembro = dnimiembro;
	}

	public String getIdMiembroConsejoFacultad() {
		return this.idMiembroConsejoFacultad;
	}

	public void setIdMiembroConsejoFacultad(String idMiembroConsejoFacultad) {
		this.idMiembroConsejoFacultad = idMiembroConsejoFacultad;
	}

	public String getNombreMiembro() {
		return this.nombreMiembro;
	}

	public void setNombreMiembro(String nombreMiembro) {
		this.nombreMiembro = nombreMiembro;
	}

	public String getApellidoPaternoMiembro() {
		return this.apellidoPaternoMiembro;
	}

	public void setApellidoPaternoMiembro(String apellidoPaternoMiembro) {
		this.apellidoPaternoMiembro = apellidoPaternoMiembro;
	}

	public String getApellidoMaternoMiembro() {
		return this.apellidoMaternoMiembro;
	}

	public void setApellidoMaternoMiembro(String apellidoMaternoMiembro) {
		this.apellidoMaternoMiembro = apellidoMaternoMiembro;
	}

	public String getDnimiembro() {
		return this.dnimiembro;
	}

	public void setDnimiembro(String dnimiembro) {
		this.dnimiembro = dnimiembro;
	}

}
