package pe.edu.consejo.facultad.unsch.entities;
// Generated 07-jun-2019 8:17:32 by Hibernate Tools 5.4.2.Final

import java.util.Date;

/**
 * Proveido generated by hbm2java
 */
public class Proveido implements java.io.Serializable {

	private String idProveido;
	private String secretarioDeActasIdSecretarioDeActas;
	private String nombre;
	private Date fechaProveido;
	private String asunto;

	public Proveido() {
	}

	public Proveido(String idProveido, String secretarioDeActasIdSecretarioDeActas, String nombre, Date fechaProveido,
			String asunto) {
		this.idProveido = idProveido;
		this.secretarioDeActasIdSecretarioDeActas = secretarioDeActasIdSecretarioDeActas;
		this.nombre = nombre;
		this.fechaProveido = fechaProveido;
		this.asunto = asunto;
	}

	public String getIdProveido() {
		return this.idProveido;
	}

	public void setIdProveido(String idProveido) {
		this.idProveido = idProveido;
	}

	public String getSecretarioDeActasIdSecretarioDeActas() {
		return this.secretarioDeActasIdSecretarioDeActas;
	}

	public void setSecretarioDeActasIdSecretarioDeActas(String secretarioDeActasIdSecretarioDeActas) {
		this.secretarioDeActasIdSecretarioDeActas = secretarioDeActasIdSecretarioDeActas;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaProveido() {
		return this.fechaProveido;
	}

	public void setFechaProveido(Date fechaProveido) {
		this.fechaProveido = fechaProveido;
	}

	public String getAsunto() {
		return this.asunto;
	}

	public void setAsunto(String asunto) {
		this.asunto = asunto;
	}

}
