package pe.edu.consejo.facultad.unsch.entities;
// Generated 28-jun-2019 1:16:48 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Proveido generated by hbm2java
 */
@Entity
@Table(name = "proveido", catalog = "consejodefacultad")
public class Proveido implements java.io.Serializable {

	private String idProveido;
	private Secretariodeactas secretariodeactas;
	private String nombre;
	private Date fechaProveido;
	private String asunto;

	public Proveido() {
	}

	public Proveido(String idProveido, Secretariodeactas secretariodeactas, String nombre, Date fechaProveido,
			String asunto) {
		this.idProveido = idProveido;
		this.secretariodeactas = secretariodeactas;
		this.nombre = nombre;
		this.fechaProveido = fechaProveido;
		this.asunto = asunto;
	}

	@Id

	@Column(name = "idProveido", unique = true, nullable = false, length = 30)
	public String getIdProveido() {
		return this.idProveido;
	}

	public void setIdProveido(String idProveido) {
		this.idProveido = idProveido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SecretarioDeActas_idSecretarioDeActas", nullable = false)
	public Secretariodeactas getSecretariodeactas() {
		return this.secretariodeactas;
	}

	public void setSecretariodeactas(Secretariodeactas secretariodeactas) {
		this.secretariodeactas = secretariodeactas;
	}

	@Column(name = "Nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FechaProveido", nullable = false, length = 10)
	public Date getFechaProveido() {
		return this.fechaProveido;
	}

	public void setFechaProveido(Date fechaProveido) {
		this.fechaProveido = fechaProveido;
	}

	@Column(name = "Asunto", nullable = false, length = 45)
	public String getAsunto() {
		return this.asunto;
	}

	public void setAsunto(String asunto) {
		this.asunto = asunto;
	}

}
