package pe.edu.consejo.facultad.unsch.entities;
// Generated 28-jun-2019 1:16:48 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Secretariodeactas generated by hbm2java
 */
@Entity
@Table(name = "secretariodeactas", catalog = "consejodefacultad")
public class Secretariodeactas implements java.io.Serializable {

	private String idSecretarioDeActas;
	private String nombreSecretario;
	private String apellidoPaternoSecretario;
	private String apellidoMaternoSecretario;
	private String dnisecretario;
	private Set<Citacion> citacions = new HashSet<Citacion>(0);
	private Set<Proveido> proveidos = new HashSet<Proveido>(0);
	private Set<Sesion> sesions = new HashSet<Sesion>(0);
	private Set<Acta> actas = new HashSet<Acta>(0);

	public Secretariodeactas() {
	}

	public Secretariodeactas(String idSecretarioDeActas, String nombreSecretario, String apellidoPaternoSecretario,
			String apellidoMaternoSecretario, String dnisecretario) {
		this.idSecretarioDeActas = idSecretarioDeActas;
		this.nombreSecretario = nombreSecretario;
		this.apellidoPaternoSecretario = apellidoPaternoSecretario;
		this.apellidoMaternoSecretario = apellidoMaternoSecretario;
		this.dnisecretario = dnisecretario;
	}

	public Secretariodeactas(String idSecretarioDeActas, String nombreSecretario, String apellidoPaternoSecretario,
			String apellidoMaternoSecretario, String dnisecretario, Set<Citacion> citacions, Set<Proveido> proveidos,
			Set<Sesion> sesions, Set<Acta> actas) {
		this.idSecretarioDeActas = idSecretarioDeActas;
		this.nombreSecretario = nombreSecretario;
		this.apellidoPaternoSecretario = apellidoPaternoSecretario;
		this.apellidoMaternoSecretario = apellidoMaternoSecretario;
		this.dnisecretario = dnisecretario;
		this.citacions = citacions;
		this.proveidos = proveidos;
		this.sesions = sesions;
		this.actas = actas;
	}

	@Id

	@Column(name = "idSecretarioDeActas", unique = true, nullable = false, length = 30)
	public String getIdSecretarioDeActas() {
		return this.idSecretarioDeActas;
	}

	public void setIdSecretarioDeActas(String idSecretarioDeActas) {
		this.idSecretarioDeActas = idSecretarioDeActas;
	}

	@Column(name = "NombreSecretario", nullable = false, length = 45)
	public String getNombreSecretario() {
		return this.nombreSecretario;
	}

	public void setNombreSecretario(String nombreSecretario) {
		this.nombreSecretario = nombreSecretario;
	}

	@Column(name = "ApellidoPaternoSecretario", nullable = false, length = 45)
	public String getApellidoPaternoSecretario() {
		return this.apellidoPaternoSecretario;
	}

	public void setApellidoPaternoSecretario(String apellidoPaternoSecretario) {
		this.apellidoPaternoSecretario = apellidoPaternoSecretario;
	}

	@Column(name = "ApellidoMaternoSecretario", nullable = false, length = 45)
	public String getApellidoMaternoSecretario() {
		return this.apellidoMaternoSecretario;
	}

	public void setApellidoMaternoSecretario(String apellidoMaternoSecretario) {
		this.apellidoMaternoSecretario = apellidoMaternoSecretario;
	}

	@Column(name = "DNISecretario", nullable = false, length = 8)
	public String getDnisecretario() {
		return this.dnisecretario;
	}

	public void setDnisecretario(String dnisecretario) {
		this.dnisecretario = dnisecretario;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "secretariodeactas")
	public Set<Citacion> getCitacions() {
		return this.citacions;
	}

	public void setCitacions(Set<Citacion> citacions) {
		this.citacions = citacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "secretariodeactas")
	public Set<Proveido> getProveidos() {
		return this.proveidos;
	}

	public void setProveidos(Set<Proveido> proveidos) {
		this.proveidos = proveidos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "secretariodeactas")
	public Set<Sesion> getSesions() {
		return this.sesions;
	}

	public void setSesions(Set<Sesion> sesions) {
		this.sesions = sesions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "secretariodeactas")
	public Set<Acta> getActas() {
		return this.actas;
	}

	public void setActas(Set<Acta> actas) {
		this.actas = actas;
	}

}
