package pe.edu.consejo.facultad.unsch.entities;
// Generated 07-jun-2019 8:17:32 by Hibernate Tools 5.4.2.Final

/**
 * Secretariodeactas generated by hbm2java
 */
public class Secretariodeactas implements java.io.Serializable {

	private String idSecretarioDeActas;
	private String nombreSecretario;
	private String apellidoPaternoSecretario;
	private String apellidoMaternoSecretario;
	private String dnisecretario;

	public Secretariodeactas() {
	}

	public Secretariodeactas(String idSecretarioDeActas, String nombreSecretario, String apellidoPaternoSecretario,
			String apellidoMaternoSecretario, String dnisecretario) {
		this.idSecretarioDeActas = idSecretarioDeActas;
		this.nombreSecretario = nombreSecretario;
		this.apellidoPaternoSecretario = apellidoPaternoSecretario;
		this.apellidoMaternoSecretario = apellidoMaternoSecretario;
		this.dnisecretario = dnisecretario;
	}

	public String getIdSecretarioDeActas() {
		return this.idSecretarioDeActas;
	}

	public void setIdSecretarioDeActas(String idSecretarioDeActas) {
		this.idSecretarioDeActas = idSecretarioDeActas;
	}

	public String getNombreSecretario() {
		return this.nombreSecretario;
	}

	public void setNombreSecretario(String nombreSecretario) {
		this.nombreSecretario = nombreSecretario;
	}

	public String getApellidoPaternoSecretario() {
		return this.apellidoPaternoSecretario;
	}

	public void setApellidoPaternoSecretario(String apellidoPaternoSecretario) {
		this.apellidoPaternoSecretario = apellidoPaternoSecretario;
	}

	public String getApellidoMaternoSecretario() {
		return this.apellidoMaternoSecretario;
	}

	public void setApellidoMaternoSecretario(String apellidoMaternoSecretario) {
		this.apellidoMaternoSecretario = apellidoMaternoSecretario;
	}

	public String getDnisecretario() {
		return this.dnisecretario;
	}

	public void setDnisecretario(String dnisecretario) {
		this.dnisecretario = dnisecretario;
	}

}
