package pe.edu.consejo.facultad.unsch.entities;
// Generated 28-jun-2019 1:16:48 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sesion generated by hbm2java
 */
@Entity
@Table(name = "sesion", catalog = "consejodefacultad")
public class Sesion implements java.io.Serializable {

	private String idSesion;
	private Decano decano;
	private Secretariodeactas secretariodeactas;
	private Date fechaSesion;
	private String horaInicio;
	private String tipoSesion;
	private String estadoSesion;

	public Sesion() {
	}

	public Sesion(String idSesion, Decano decano, Secretariodeactas secretariodeactas, Date fechaSesion,
			String horaInicio, String tipoSesion, String estadoSesion) {
		this.idSesion = idSesion;
		this.decano = decano;
		this.secretariodeactas = secretariodeactas;
		this.fechaSesion = fechaSesion;
		this.horaInicio = horaInicio;
		this.tipoSesion = tipoSesion;
		this.estadoSesion = estadoSesion;
	}

	@Id

	@Column(name = "idSesion", unique = true, nullable = false, length = 30)
	public String getIdSesion() {
		return this.idSesion;
	}

	public void setIdSesion(String idSesion) {
		this.idSesion = idSesion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Decano_idDecano", nullable = false)
	public Decano getDecano() {
		return this.decano;
	}

	public void setDecano(Decano decano) {
		this.decano = decano;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SecretarioDeActas_idSecretarioDeActas", nullable = false)
	public Secretariodeactas getSecretariodeactas() {
		return this.secretariodeactas;
	}

	public void setSecretariodeactas(Secretariodeactas secretariodeactas) {
		this.secretariodeactas = secretariodeactas;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FechaSesion", nullable = false, length = 10)
	public Date getFechaSesion() {
		return this.fechaSesion;
	}

	public void setFechaSesion(Date fechaSesion) {
		this.fechaSesion = fechaSesion;
	}

	@Column(name = "HoraInicio", nullable = false, length = 45)
	public String getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(String horaInicio) {
		this.horaInicio = horaInicio;
	}

	@Column(name = "TipoSesion", nullable = false, length = 45)
	public String getTipoSesion() {
		return this.tipoSesion;
	}

	public void setTipoSesion(String tipoSesion) {
		this.tipoSesion = tipoSesion;
	}

	@Column(name = "EstadoSesion", nullable = false, length = 15)
	public String getEstadoSesion() {
		return this.estadoSesion;
	}

	public void setEstadoSesion(String estadoSesion) {
		this.estadoSesion = estadoSesion;
	}

}
