package pe.edu.consejo.facultad.unsch.entities;
// Generated 07-jun-2019 8:17:32 by Hibernate Tools 5.4.2.Final

import java.util.Date;

/**
 * Sesion generated by hbm2java
 */
public class Sesion implements java.io.Serializable {

	private String idSesion;
	private Date fechaSesion;
	private String horaInicio;
	private String tipoSesion;
	private String estadoSesion;
	private String decanoIdDecano;
	private String secretarioDeActasIdSecretarioDeActas;

	public Sesion() {
	}

	public Sesion(String idSesion, Date fechaSesion, String horaInicio, String tipoSesion, String estadoSesion,
			String decanoIdDecano, String secretarioDeActasIdSecretarioDeActas) {
		this.idSesion = idSesion;
		this.fechaSesion = fechaSesion;
		this.horaInicio = horaInicio;
		this.tipoSesion = tipoSesion;
		this.estadoSesion = estadoSesion;
		this.decanoIdDecano = decanoIdDecano;
		this.secretarioDeActasIdSecretarioDeActas = secretarioDeActasIdSecretarioDeActas;
	}

	public String getIdSesion() {
		return this.idSesion;
	}

	public void setIdSesion(String idSesion) {
		this.idSesion = idSesion;
	}

	public Date getFechaSesion() {
		return this.fechaSesion;
	}

	public void setFechaSesion(Date fechaSesion) {
		this.fechaSesion = fechaSesion;
	}

	public String getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(String horaInicio) {
		this.horaInicio = horaInicio;
	}

	public String getTipoSesion() {
		return this.tipoSesion;
	}

	public void setTipoSesion(String tipoSesion) {
		this.tipoSesion = tipoSesion;
	}

	public String getEstadoSesion() {
		return this.estadoSesion;
	}

	public void setEstadoSesion(String estadoSesion) {
		this.estadoSesion = estadoSesion;
	}

	public String getDecanoIdDecano() {
		return this.decanoIdDecano;
	}

	public void setDecanoIdDecano(String decanoIdDecano) {
		this.decanoIdDecano = decanoIdDecano;
	}

	public String getSecretarioDeActasIdSecretarioDeActas() {
		return this.secretarioDeActasIdSecretarioDeActas;
	}

	public void setSecretarioDeActasIdSecretarioDeActas(String secretarioDeActasIdSecretarioDeActas) {
		this.secretarioDeActasIdSecretarioDeActas = secretarioDeActasIdSecretarioDeActas;
	}

}
